import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import Navbar from "./components/Navbar";
import { Toaster } from './../components/ui/toaster';
import Footer from "./components/Footer";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./components/appSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            
            
            <div className=" w-full h-full bg-orange-100/2 dark:bg-[#0C0A09]">
            
            
              <div className=" w-screen z-30 bg-orange-100 dark:bg-[#121212]/50 sticky top-0 "><Navbar /></div>
              <SidebarProvider >
              <div className="z-50 max-h-screen sticky top-20 text-primary bg-orange-100 dark:bg-[#121212]/50"><SidebarTrigger /></div>
              <div className="bg-orange-100 dark:bg-[#121212] z-40"><AppSidebar /></div>
            
              <main className="max-w-screen-2xl mx-auto px-4 mb-10">
              
                {children}</main>
                </SidebarProvider>
              <div className="z-40 w-screen bg-orange-100 dark:bg-[#0C0A09]"><Footer /></div>
            </div>
            <Toaster/>
            
          </ThemeProvider>
          
      </body>
    </html>
  );
}
